_wandb:
    value:
        cli_version: 0.22.2
        e:
            nzywrrs8z27tg9b0lhyb0qzje0jfbwor:
                args:
                    - --node-ip-address=10.249.42.56
                    - --node-manager-port=38393
                    - --object-store-name=/tmp/ray/session_2026-03-17_21-47-35_270830_1089042/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2026-03-17_21-47-35_270830_1089042/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=54575
                    - --runtime-env-agent-port=50604
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=50604
                    - --gcs-address=10.249.42.56:60840
                    - --session-name=session_2026-03-17_21-47-35_270830_1089042
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=d554f7af9c1a01a3be1dbddc8a07cff6265630b5c1dff04be7a6390d
                    - --startup-token=112
                    - --worker-launch-time-ms=1773755259393
                    - --node-id=9c1616145cb886c792af95fe2c4f0a8567e65b939d059f96f966a363
                    - --runtime-env-hash=462212841
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "527295578112"
                        used: "125874843648"
                email: hiluofeng@gmail.com
                executable: /home/luofeng/anaconda3/envs/verl/bin/python3
                git:
                    commit: b5e711eab5da5c0f0d23856246e81085eed7b543
                    remote: https://github.com/volcengine/verl
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-8a671b40-6fcb-5aab-1155-f284a2af557e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-0013f2e6-3547-1101-0a9b-e0ee03fc9a44
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-04ba7edb-8a95-8d82-3294-142bdbb8ab03
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-8adb709e-856c-0a94-c6eb-f5820fa1e6aa
                host: 2haoji-A100
                memory:
                    total: "236252397568"
                os: Linux-5.15.0-102-generic-x86_64-with-glibc2.31
                program: /home/luofeng/anaconda3/envs/verl/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.0
                root: /data1/luofeng/RL/verl
                startedAt: "2026-03-17T13:51:24.866138Z"
                writerId: nzywrrs8z27tg9b0lhyb0qzje0jfbwor
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.22.2
            "6": 4.51.1
            "12": 0.22.2
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            checkpoint:
                load_contents:
                    - model
                    - optimizer
                    - extra
                save_contents:
                    - model
                    - optimizer
                    - extra
            clip_ratio: 0.2
            clip_ratio_c: 3
            clip_ratio_high: 0.2
            clip_ratio_low: 0.2
            entropy_checkpointing: false
            entropy_coeff: 0
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                model_dtype: bfloat16
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.001
            kl_loss_type: low_var_kl
            loss_agg_mode: seq-mean-token-sum-norm
            optim:
                lr: 2e-05
                lr_warmup_steps: -1
                lr_warmup_steps_ratio: 0
                min_lr_ratio: 0
                num_cycles: 0.5
                total_training_steps: 240
                warmup_style: constant
                weight_decay: 0.01
            policy_loss:
                clip_cov_lb: 1
                clip_cov_ratio: 0.0002
                clip_cov_ub: 5
                kl_cov_ratio: 0.0002
                loss_mode: vanilla
                ppo_kl_coef: 0.1
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 16384
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: 1
            ppo_mini_batch_size: 8
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: true
            use_kl_loss: false
            use_torch_compile: true
        hybrid_engine: true
        model:
            custom_chat_template: null
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            exclude_modules: null
            external_lib: null
            fused_kernel_options:
                impl_backend: torch
            lora_alpha: 64
            lora_rank: 32
            path: /data1/luofeng/RL/checkpoints/c2rust-sft-no-step/qwen2.5-7B/global_step_2529
            target_modules: all-linear
            trust_remote_code: false
            use_fused_kernels: false
            use_liger: false
            use_remove_padding: true
            use_shm: false
        ref:
            entropy_checkpointing: false
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 1
            log_prob_use_dynamic_bsz: true
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        rollout:
            agent:
                custom_async_server:
                    name: null
                    path: null
                num_workers: 8
            calculate_log_probs: false
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: false
            engine_kwargs:
                sglang:
                    attention_backend: null
                vllm:
                    disable_mm_preprocessor_cache: false
                    swap_space: null
            free_cache_engine: true
            gpu_memory_utilization: 0.8
            ignore_eos: false
            layered_summon: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 1
            log_prob_use_dynamic_bsz: true
            max_model_len: null
            max_num_batched_tokens: 2048
            max_num_seqs: 8
            mode: sync
            multi_stage_wake_up: false
            multi_turn:
                completion_callback: null
                enable: false
                format: hermes
                interaction_config_path: null
                max_assistant_turns: null
                max_parallel_calls: 1
                max_tool_response_length: 256
                max_user_turns: null
                tokenization_sanity_check_mode: strict
                tool_config_path: null
                tool_response_truncate_side: middle
                use_inference_chat_template: false
            "n": 2
            name: vllm
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            prompt_length: 1024
            response_length: 1024
            temperature: 1
            tensor_model_parallel_size: 1
            top_k: -1
            top_p: 1
            val_kwargs:
                do_sample: false
                "n": 1
                temperature: 0
                top_k: -1
                top_p: 1
algorithm:
    value:
        _target_: verl.trainer.config.AlgoConfig
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            _target_: verl.trainer.config.KLControlConfig
            horizon: 10000
            kl_coef: 0.001
            target_kl: 0.1
            type: fixed
        kl_penalty: kl
        lam: 1
        norm_adv_by_std_in_grpo: true
        pf_ppo:
            _target_: verl.trainer.config.PFPPOConfig
            reweight_method: pow
            weight_pow: 2
        use_kl_in_reward: false
        use_pf_ppo: false
critic:
    value:
        checkpoint:
            load_contents:
                - model
                - optimizer
                - extra
            save_contents:
                - model
                - optimizer
                - extra
        cliprange_value: 0.5
        enable: false
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        loss_agg_mode: seq-mean-token-sum-norm
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            lora_alpha: 16
            lora_rank: 0
            path: ~/models/deepseek-llm-7b-chat
            target_modules: all-linear
            tokenizer_path: /data1/luofeng/RL/checkpoints/c2rust-sft-no-step/qwen2.5-7B/global_step_2529
            trust_remote_code: false
            use_remove_padding: false
            use_shm: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 240
            warmup_style: constant
            weight_decay: 0.01
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 8
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        rollout_n: 2
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
custom_reward_function:
    value:
        name: compute_execution_reward
        path: /data1/luofeng/RL/verl/reward_fn/c2rust_step.py
data:
    value:
        custom_cls:
            name: null
            path: null
        dataloader_num_workers: 8
        filter_overlong_prompts: false
        filter_overlong_prompts_workers: 1
        image_key: images
        max_prompt_length: 1024
        max_response_length: 1024
        prompt_key: prompt
        return_full_prompt: false
        return_multi_modal_inputs: true
        return_raw_chat: false
        return_raw_input_ids: false
        reward_fn_key: reward_type
        sampler:
            class_name: null
            class_path: null
        shuffle: true
        tokenizer: null
        train_batch_size: 32
        train_files: /data1/luofeng/RL/verl/data/rl_data/train_no_step_small.parquet
        truncation: error
        trust_remote_code: false
        use_shm: false
        val_batch_size: null
        val_files: /data1/luofeng/RL/verl/data/rl_data/test_no_step_small.parquet
        validation_shuffle: false
        video_key: videos
ray_init:
    value:
        num_cpus: null
        timeline_json_file: null
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        launch_reward_fn_async: false
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            input_tokenizer: /data1/luofeng/RL/checkpoints/c2rust-sft-no-step/qwen2.5-7B/global_step_2529
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            trust_remote_code: false
            use_fused_kernels: false
            use_remove_padding: false
            use_shm: false
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        reward_manager: naive
        sandbox_fusion:
            max_concurrent: 64
            memory_limit_mb: 1024
            url: null
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
trainer:
    value:
        balance_batch: true
        controller_nsight_options:
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            trace: cuda,nvtx,cublas,ucx
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: /data1/luofeng/RL/checkpoints/c2rust-rl/qwen2.5-7B-no-step-grpo
        del_local_ckpt_after_load: false
        device: cuda
        esi_redundant_time: 0
        experiment_name: qwen2.5-7B-no-step-grpo
        log_val_generations: 0
        logger:
            - console
            - wandb
        max_actor_ckpt_to_keep: null
        max_critic_ckpt_to_keep: null
        n_gpus_per_node: 2
        nnodes: 1
        npu_profile:
            options:
                analysis: true
                level: level1
                record_shapes: false
                save_path: ./profiler_data
                with_cpu: true
                with_memory: false
                with_module: false
                with_npu: true
                with_stack: false
        profile_steps: null
        project_name: c2rust-rl
        ray_wait_register_center_timeout: 300
        resume_from_path: null
        resume_mode: disable
        rollout_data_dir: null
        save_freq: 15
        test_freq: 1
        total_epochs: 3
        total_training_steps: null
        val_before_train: true
        val_only: false
        validation_data_dir: null
        worker_nsight_options:
            capture-range: cudaProfilerApi
            capture-range-end: null
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            kill: none
            trace: cuda,nvtx,cublas,ucx
